// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rock.DataAccess.Data;

#nullable disable

namespace Rock.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231108092948_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rock.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "John"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Cherry"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Snow"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            Name = "Snow"
                        });
                });

            modelBuilder.Entity("Rock.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            CategoryId = 1,
                            Description = "Abc Egh",
                            ISBN = "ISBN",
                            ListPrice = 40.0,
                            Price = 50.0,
                            Price100 = 100.0,
                            Price50 = 5.7000000000000002,
                            Title = "Action",
                            imgURL = ""
                        },
                        new
                        {
                            Id = 2,
                            Author = "John Doe",
                            CategoryId = 2,
                            Description = "Abc Egh",
                            ISBN = "ISBN",
                            ListPrice = 40.0,
                            Price = 50.0,
                            Price100 = 100.0,
                            Price50 = 5.7000000000000002,
                            Title = "Action",
                            imgURL = ""
                        },
                        new
                        {
                            Id = 3,
                            Author = "John Doe",
                            CategoryId = 3,
                            Description = "Abc Egh",
                            ISBN = "ISBN",
                            ListPrice = 40.0,
                            Price = 50.0,
                            Price100 = 100.0,
                            Price50 = 5.7000000000000002,
                            Title = "Action",
                            imgURL = ""
                        },
                        new
                        {
                            Id = 4,
                            Author = "John Doe",
                            CategoryId = 4,
                            Description = "Abc Egh",
                            ISBN = "ISBN",
                            ListPrice = 40.0,
                            Price = 50.0,
                            Price100 = 100.0,
                            Price50 = 5.7000000000000002,
                            Title = "Action",
                            imgURL = ""
                        },
                        new
                        {
                            Id = 5,
                            Author = "John Doe",
                            CategoryId = 5,
                            Description = "Abc Egh",
                            ISBN = "ISBN",
                            ListPrice = 40.0,
                            Price = 50.0,
                            Price100 = 100.0,
                            Price50 = 5.7000000000000002,
                            Title = "Action",
                            imgURL = ""
                        },
                        new
                        {
                            Id = 6,
                            Author = "John Doe",
                            CategoryId = 1,
                            Description = "Abc Egh",
                            ISBN = "ISBN",
                            ListPrice = 40.0,
                            Price = 50.0,
                            Price100 = 100.0,
                            Price50 = 5.7000000000000002,
                            Title = "Action",
                            imgURL = ""
                        });
                });

            modelBuilder.Entity("Rock.Models.Product", b =>
                {
                    b.HasOne("Rock.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
